skillMetadata:
   sections:
      - name: Web Terminal
        fields:
          - name: terminal_port
            type: text
            label: web Terminal Port
            value: "8022"
          - name: terminal_enabled
            type: checkbox
            label: Auto start Web Termial
            value: "False"
      - name: Web CLI client
        fields:
          - name: cli_port
            type: text
            label: web CLI client Port
            value: "8080"
          - name: cli_enabled
            type: checkbox
            label: Auto start Web CLI Client
            value: "True"
